# https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2"] }

#[[language]]
#name = "css"
#formatter = { command = "prettier", args = ["--parser", "css"] }

#[[language]]
#name = "html"
#formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "ini"
file-types = ["ini", { suffix = "kitty.conf" }] # FIXME

[[language]]
name = "javascript"
auto-format = true
# formatter = { command = "prettier", args = ["--parser", "typescript"] }
# formatter = { command = "deno", args = ["fmt", "-", "--ext", "js" ] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "jsx"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
# formatter = { command = "deno", args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "lua"
auto-format = true
# PR: current file in formatter args https://github.com/helix-editor/helix/pull/5626
# formatter = { command = "stylua", args = ["--search-parent-directories", "--stdin-filepath", "{}", "-"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
# formatter = { command = "deno", args = ["fmt", "-", "--ext", "md"] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"] }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = ["--emit=stdout"] }

[language.config]
checkOnSave = { command = "clippy" }
# rust-analyzer.cargo.features = "all"

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }
# https://github.com/helix-editor/helix/issues/5174#issuecomment-1353668616
language-server = { command = "" }

[[language]]
name = "typescript"
auto-format = true
#formatter = { command = "prettier", args = ["--parser", "typescript"] }
# formatter = { command = "deno", args = ["fmt", "-", "--ext", "ts" ] }
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
# config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "tsx"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
